http://localhost:4000/
### 
http://localhost:3000/status
###
http://localhost:4000/blocks
###
POST http://localhost:4000/blocks

###
http://localhost:4000/blocks/89ac3bc575e876952b0b32e19deeb0b1abfa57175c51779b92cf571cc7dfd4fa
###
http://localhost:4000/balance/4b71030fb550017bea517c9e06deef6315ab0bc3c8aacfed9c25c2c61f3ce9fc961ea86e395e97f6c822ad1db80dfddb106ca247510178eec5c4cf70e29ae0f8?total=true
###
http://localhost:4000/balance/kozel
###
http://localhost:4000/balance/nico?total=true
###
POST http://localhost:4000/transactions

{
    "to":"kozel",
    "amount": 15
}
###
http://localhost:4000/mempool
###
http://localhost:4000/wallet
###
POST http://localhost:4000/peers

{
    "address": "127.0.0.1",
    "port": "3000"
}
###
http://localhost:4000/peers